// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXo8XxUkzEES6fNksSkzE6OlNXQhxY350',
    appId: '1:205740608962:web:02276046d31642316bda5b',
    messagingSenderId: '205740608962',
    projectId: 'taskify-e4b68',
    authDomain: 'taskify-e4b68.firebaseapp.com',
    storageBucket: 'taskify-e4b68.firebasestorage.app',
    measurementId: 'G-3PG3M2YZ35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx1VqEUvO2OxhkbTIMfSKW5epUDTfDyzo',
    appId: '1:205740608962:android:d9afcd95e8210b6c6bda5b',
    messagingSenderId: '205740608962',
    projectId: 'taskify-e4b68',
    storageBucket: 'taskify-e4b68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA95Byuu8o95szUl7sOeCr6IjfqllQhgT8',
    appId: '1:205740608962:ios:f5e4268c3bb2e69a6bda5b',
    messagingSenderId: '205740608962',
    projectId: 'taskify-e4b68',
    storageBucket: 'taskify-e4b68.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA95Byuu8o95szUl7sOeCr6IjfqllQhgT8',
    appId: '1:205740608962:ios:f5e4268c3bb2e69a6bda5b',
    messagingSenderId: '205740608962',
    projectId: 'taskify-e4b68',
    storageBucket: 'taskify-e4b68.firebasestorage.app',
    iosBundleId: 'com.example.taskify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXo8XxUkzEES6fNksSkzE6OlNXQhxY350',
    appId: '1:205740608962:web:dcca46b9db336b996bda5b',
    messagingSenderId: '205740608962',
    projectId: 'taskify-e4b68',
    authDomain: 'taskify-e4b68.firebaseapp.com',
    storageBucket: 'taskify-e4b68.firebasestorage.app',
    measurementId: 'G-ZHRDST0V03',
  );
}
